services:
  frontend:
    container_name: seniorlab-frontend
    build:
      context: ./Frontend
    ports:
      - "9911:5173"
      - "4000:4000"
    environment:
      - VITE_OPEN_AI_ENDPOINT=http://132.226.195.28:8468/
      - REACT_APP_API_ENDPOINT=http://132.226.195.28:8000/api/data
    depends_on:
      - backend
    networks:
      - schoolproject_app_network
    labels:
      caddy: "ai.seniorlab.ba"
      caddy.reverse_proxy: "{{upstreams 5173}}"
      caddy_2: "api.seniorlab.ba"
      caddy_2.reverse_proxy: "{{upstreams 4000}}"

  backend:
    container_name: seniorlab-backend
    ports:
      - "1469:8468"
    build:
      context: ./Backend
    env_file:
      - ./Backend/.env
    networks:
      - schoolproject_app_network

networks:
  schoolproject_app_network:
    external: true

volumes:
  caddy_data_seniorlab: